### ISSUE TITLE
运行报错，java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Ykcxr** [dangfan/android-ndk-openssl#1]
terro，你好！非常感谢你为大家提供了这个在Android中应用OpenSSL的demo！但是，在我这里运行会报错，错误日志如下：
```
3-14 17:30:48.402 3617-3617/com.example.openssltest E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.example.openssltest, PID: 3617
                                                                       java.lang.UnsatisfiedLinkError: No implementation found for byte[] com.example.openssltest.MainActivity.hmacSha256(byte[]) (tried Java_com_example_openssltest_MainActivity_hmacSha256 and Java_com_example_openssltest_MainActivity_hmacSha256___3B)
                                                                           at com.example.openssltest.MainActivity.hmacSha256(Native Method)
                                                                           at com.example.openssltest.MainActivity.onCreate(MainActivity.java:14)
                                                                           at android.app.Activity.performCreate(Activity.java:6251)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```
我查了一下这个错误原因，网上大多数情况都是因为JNI的方法名称定义没有按照规定定义，可是在你的demo里面可以看到JNI的方法名称定义是没有问题的，所以不知道问题出在哪里，还望不吝赐教！

**Comment by dangfan** [comment]
请问你的安卓是什么版本？从 6.0 开始，Google 要求不要使用系统的 OpenSSL，请见：https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html?hl=zh-cn
